/**
 * 청년원스톱 mock fixture — 온통청년·고용24·LH·HRD-Net·서민금융 5종 요약본.
 *
 * 실데이터 규격은 제안서 §4 참고. 본 fixture 는 스키마 재현용이며
 * 공공데이터 API 키 부재 시에도 5대 화면 전부 시연 가능하도록 구성된다.
 */

import type { JobPost, Policy } from "./types";

export const MOCK_POLICIES: Policy[] = [
  {
    id: "ONT-2026-001",
    source: "온통청년",
    title: "청년 월세 한시 특별지원",
    category: "주거",
    region: "전국",
    ageMin: 19,
    ageMax: 34,
    incomeTier: ["low", "mid"],
    housing: ["rent"],
    employment: ["student", "job_seeker", "employed", "freelancer"],
    deadline: "2026-06-30",
    summary: "월 최대 20만원, 최대 12개월 월세 지원. 청년 본인 명의 임차 계약 필수.",
    documents: ["주민등록등본", "임대차계약서 사본", "통장 사본", "가족관계증명서"],
    url: "https://www.youthcenter.go.kr",
  },
  {
    id: "ONT-2026-002",
    source: "온통청년",
    title: "청년도약계좌",
    category: "금융",
    region: "전국",
    ageMin: 19,
    ageMax: 34,
    incomeTier: ["low", "mid", "high"],
    employment: ["employed", "freelancer", "starter"],
    deadline: "2026-12-31",
    summary: "5년 만기 적금 · 정부 기여금 매월 최대 3.3만원 + 이자소득 비과세.",
    documents: ["신분증", "소득확인서류", "가구원 동의서"],
    url: "https://www.youthcenter.go.kr",
  },
  {
    id: "LH-2026-101",
    source: "LH",
    title: "청년 매입임대주택 입주자 모집",
    category: "주거",
    region: "서울",
    ageMin: 19,
    ageMax: 39,
    incomeTier: ["low", "mid"],
    housing: ["rent", "family"],
    deadline: "2026-05-20",
    summary: "시세 대비 40~50% 임대료 · 최대 6년 거주 · 무주택 세대구성원 기준.",
    documents: ["주민등록등본", "무주택 확인서", "소득 확인 서류", "혼인관계증명서"],
    url: "https://apply.lh.or.kr",
  },
  {
    id: "EMP-2026-210",
    source: "고용24",
    title: "국민취업지원제도 I형",
    category: "취업",
    region: "전국",
    ageMin: 15,
    ageMax: 69,
    incomeTier: ["low", "mid"],
    employment: ["job_seeker", "freelancer"],
    deadline: "2026-12-31",
    summary: "구직촉진수당 월 50만원 × 6개월 + 취업지원 프로그램.",
    documents: ["신분증", "가구원 구성 확인서", "소득·재산 확인"],
    url: "https://work.go.kr",
  },
  {
    id: "HRD-2026-501",
    source: "HRD-Net",
    title: "K-디지털 트레이닝 (풀스택 과정)",
    category: "교육",
    region: "서울",
    ageMin: 19,
    ageMax: 34,
    incomeTier: ["low", "mid", "high"],
    employment: ["student", "job_seeker", "employed"],
    deadline: "2026-05-10",
    summary: "5개월 집중 · 국민내일배움카드로 수강료 100% 지원 + 훈련수당.",
    documents: ["국민내일배움카드", "신분증", "최종학력증명서"],
    url: "https://www.hrd.go.kr",
  },
  {
    id: "FIN-2026-330",
    source: "서민금융",
    title: "청년 햇살론 유스",
    category: "금융",
    region: "전국",
    ageMin: 19,
    ageMax: 34,
    incomeTier: ["low", "mid"],
    employment: ["student", "job_seeker", "employed", "freelancer"],
    deadline: "2026-12-31",
    summary: "연 3.6~4.5% 저금리 · 최대 1,200만원 생계자금. 신용 하위자 우선.",
    documents: ["신분증", "재직/재학 증빙", "소득증빙", "주거 증빙"],
    url: "https://www.kinfa.or.kr",
  },
  {
    id: "ONT-2026-003",
    source: "온통청년",
    title: "청년 창업 자금 지원",
    category: "창업",
    region: "전국",
    ageMin: 19,
    ageMax: 39,
    incomeTier: ["low", "mid", "high"],
    employment: ["starter", "freelancer"],
    deadline: "2026-07-15",
    summary: "최대 1억원 저리융자 + 창업교육 + 공간 지원. 사업자등록 3년 이내.",
    documents: ["사업계획서", "사업자등록증", "신분증"],
    url: "https://www.youthcenter.go.kr",
  },
  {
    id: "LH-2026-102",
    source: "LH",
    title: "청년 전세임대주택",
    category: "주거",
    region: "경기",
    ageMin: 19,
    ageMax: 39,
    incomeTier: ["low", "mid"],
    housing: ["rent", "dorm", "family"],
    deadline: "2026-08-31",
    summary: "최대 1.2억 전세 지원 · 본인 거주 지역 자유 선택 · 6년 거주.",
    documents: ["주민등록등본", "소득 증빙", "임대차계약서(가계약 가능)"],
    url: "https://apply.lh.or.kr",
  },
  {
    id: "EMP-2026-211",
    source: "고용24",
    title: "청년 일자리 도약장려금",
    category: "취업",
    region: "전국",
    ageMin: 19,
    ageMax: 34,
    incomeTier: ["low", "mid", "high"],
    employment: ["employed"],
    deadline: "2026-10-31",
    summary: "신규 채용 청년 1인당 월 60만원 × 12개월 기업 지원.",
    documents: ["4대보험 가입 확인", "근로계약서"],
    url: "https://work.go.kr",
  },
  {
    id: "ONT-2026-004",
    source: "온통청년",
    title: "청년 내일채움공제 (2년형)",
    category: "금융",
    region: "전국",
    ageMin: 19,
    ageMax: 34,
    incomeTier: ["low", "mid"],
    employment: ["employed"],
    deadline: "2026-12-31",
    summary: "2년 근속 시 본인 300만 + 기업 400만 + 정부 900만 = 1,600만원.",
    documents: ["근로계약서", "가입신청서", "통장사본"],
    url: "https://www.youthcenter.go.kr",
  },
  {
    id: "ONT-2026-005",
    source: "온통청년",
    title: "청년 마음건강 지원사업",
    category: "복지",
    region: "전국",
    ageMin: 19,
    ageMax: 34,
    incomeTier: ["low", "mid", "high"],
    deadline: "2026-11-30",
    summary: "심리상담 10회 무료 + 자가검진 도구 제공.",
    documents: ["신청서", "개인정보 동의서"],
    url: "https://www.youthcenter.go.kr",
  },
  {
    id: "HRD-2026-502",
    source: "HRD-Net",
    title: "국민내일배움카드 발급",
    category: "교육",
    region: "전국",
    ageMin: 15,
    ageMax: 99,
    incomeTier: ["low", "mid", "high"],
    deadline: "2026-12-31",
    summary: "5년간 최대 500만원 훈련비 지원. 모든 성인 발급 가능.",
    documents: ["신분증", "직종 선택서"],
    url: "https://www.hrd.go.kr",
  },
];

export const MOCK_JOBS: JobPost[] = [
  {
    id: "JOB-W-001",
    source: "고용24",
    title: "스타트업 프론트엔드 개발자",
    company: "(주)테크앤픽",
    region: "서울",
    category: "일자리",
    deadline: "2026-05-08",
    wage: "연 3,800~4,500만원",
    summary: "React/Next.js 경험 1년+. 청년내일채움공제 가입 가능 기업.",
  },
  {
    id: "JOB-W-002",
    source: "워크넷",
    title: "공공데이터 품질관리 사원",
    company: "(재)한국지역정보개발원",
    region: "서울",
    category: "일자리",
    deadline: "2026-05-15",
    wage: "연 3,200만원",
    summary: "공공데이터포털 품질검수 업무. 전공 무관, SQL 가능자.",
  },
  {
    id: "JOB-T-001",
    source: "HRD-Net",
    title: "데이터 분석 부트캠프 (6개월)",
    company: "멀티캠퍼스",
    region: "서울",
    category: "훈련",
    deadline: "2026-05-10",
    summary: "국민내일배움카드 100% + 훈련수당. Python/SQL/Tableau.",
  },
  {
    id: "JOB-T-002",
    source: "HRD-Net",
    title: "UI/UX 디자인 실무 과정",
    company: "패스트캠퍼스",
    region: "경기",
    category: "훈련",
    deadline: "2026-05-20",
    summary: "Figma 집중 · 12주 · K-디지털 플랫폼 연계.",
  },
  {
    id: "JOB-T-003",
    source: "HRD-Net",
    title: "AI 엔지니어링 실무",
    company: "코드스테이츠",
    region: "서울",
    category: "훈련",
    deadline: "2026-05-25",
    summary: "PyTorch / LLM 파인튜닝 중심. 취업 연계 100%.",
  },
];
